export const ar = {
    headerTitle: "أهلاً بك في أماديوس",
    tabHotels: "فنادق",
    tabVisas: "تأشيرات",
    tabSchools: "مدارس",
    searchPlaceholder: "أين تريد أن تذهب؟",
    selectDatesPlaceholder: "اختر التواريخ",
    searchButton: "بحث",
    guestsHeader: "الضيوف والغرف",
    guestsRooms: "غرف",
    guestsAdults: "بالغون",
    guestsChildren: "أطفال",
    childrenSubtitle: "أعمار 0-17",
    currency: "ريال سعودي",
    continueButton: "استمر",
    calendarHeader: "اختر التواريخ",
    calendarConfirm: "تأكيد",
    explore: "اكتشف",
    hotels: "فنادق",
    apartments: "شقق",
    villas: "فلل",
    business: "أعمال",
    selectChildAge: "اختر عمر الطفل",
    ageOptions: [
      "0 سنة", "1 سنة", "2 سنة", "3 سنوات", "4 سنوات", "5 سنوات", "6 سنوات", "7 سنوات", "8 سنوات", "9 سنوات", "10 سنوات",
      "11 سنة", "12 سنة", "13 سنة", "14 سنة", "15 سنة", "16 سنة", "17 سنة"
    ],
    searchScreenTitle: "وجهة البحث",
};
